server:
  port: 8081
spring:
  config:
    import: "optional:configserver:http://localhost:8989/"
    
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    
  datasource:
    username: POSTGRES
    password: ROOT
    url: jdbc:postgresql://localhost:3001/accountsdb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
 
    
  
  profiles:
    active: "prod"
  application:
    name: account
  
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true
      
       